name: Compile and push web image on release

# Controls when the workflow will run
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # login with Docker
      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          # generate some credentials from Dockerhub and store them into the repo secrets
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      # prepare buildx for docker
      - uses: docker/setup-buildx-action@v2
        name: Set up Docker Buildx

      # build an push the newly created image
      - uses: docker/build-push-action@v3
        name: Build and push front
        with:
          context: ./
          file: ./apps/frontend/web/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_IMAGE_NAME_FRONT_PROD}}:latest,${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_IMAGE_NAME_FRONT_PROD }}:${{ github.sha }},${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_IMAGE_NAME_FRONT_PROD }}:${{ github.event.release.name }}

      - uses: docker/setup-buildx-action@v2
        name: Set up Docker Buildx
        
      - uses: docker/build-push-action@v3
        name: Build and push back
        with:
          context: ./
          file: ./apps/backend/api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_IMAGE_NAME_BACK_PROD}}:latest,${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_IMAGE_NAME_BACK_PROD }}:${{ github.sha }},${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_IMAGE_NAME_BACK_PROD }}:${{ github.event.release.name }}